version: '3'

services:
    mongo-express:
        image: mongo-express
        container_name: mongodb-gui
        ports:
            - 8081:8081
        environment:
            - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_USER}
            - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_PASS}
            - ME_CONFIG_MONGODB_PORT=${MONGO_PORT}
            - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER}
            - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASS}
        links:
            - mongo
        networks:
            - mongo-compose-network

    mongo:
        image: mongo
        container_name: mongodb
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASS}
            - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
        ports:
            - 27017:27017
        volumes:
            - /home/matheus/Dev/mongodb:/data/db
            - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
        networks:
            - mongo-compose-network

networks: 
    mongo-compose-network:
        driver: bridge
