version: '3'

services:
  db:
    image: mongo
    container_name: db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASS}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    ports:
      - 27017:27017
    volumes:
      - ./mdb-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  #db-gui:
  #  image: mongo-express
  #  ports:
  #    - 8081:8081
  #  depends_on:
  #    - db
  #  environment:
  #    - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_USER}
  #    - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_PASS}
  #    - ME_CONFIG_MONGODB_PORT=${MONGO_PORT}
  #    - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER}
  #    - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASS}

  api:
    ##build: .
    image: api
    container_name: api
    depends_on:
      - db
    ports:
      - 4000:4000