version: '3'

services:
  mongo:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=api
    ports:
      - 27017:27017
    volumes:
      - ./mdb-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - mongo-compose-network

  mongo-express:
    image: mongo-express
    container_name: mongodb-gui
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=mongo
      - ME_CONFIG_BASICAUTH_PASSWORD=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
    links:
      - mongo
    networks:
      - mongo-compose-network

  #api:
    ##build: .
  #  image: api
  #  container_name: api
  #  depends_on:
  #    - db
  #  ports:
  #    - 4000:4000

networks: 
  mongo-compose-network:
    driver: bridge